# Generated by Django 3.2.9 on 2021-12-09 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care_always_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='patients',
            field=models.ManyToManyField(related_name='providers', through='care_always_api.UserProvider', to=settings.AUTH_USER_MODEL),
        ),
    ]
