# Generated by Django 3.2.9 on 2021-12-10 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_always_api', '0002_provider_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='care_always_api.appointment'),
        ),
    ]
