# Generated by Django 3.2.9 on 2021-12-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_always_api', '0004_alter_question_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_always_api.appointment'),
        ),
    ]
